"""
Medicine-to-Disease Mapping Database
Covers 30+ common medications with associated diseases, severity,
and symptom profiles. Used for cross-referencing OCR output.
"""

MEDICINE_DB = {
    "amoxicillin":    {"diseases": ["pneumonia", "bronchitis", "sinusitis"],
                       "severity": "moderate", "symptoms": ["fever", "cough", "congestion"]},
    "azithromycin":   {"diseases": ["pneumonia", "bronchitis", "otitis"],
                       "severity": "moderate", "symptoms": ["fever", "sore throat", "cough"]},
    "metformin":      {"diseases": ["diabetes type 2"],
                       "severity": "chronic", "symptoms": ["polyuria", "polydipsia", "fatigue"]},
    "insulin":        {"diseases": ["diabetes type 1", "diabetes type 2"],
                       "severity": "severe", "symptoms": ["hyperglycemia", "ketoacidosis"]},
    "lisinopril":     {"diseases": ["hypertension", "heart failure"],
                       "severity": "chronic", "symptoms": ["high blood pressure", "edema"]},
    "atorvastatin":   {"diseases": ["hypercholesterolemia", "cardiovascular disease"],
                       "severity": "chronic", "symptoms": ["chest pain", "fatigue"]},
    "omeprazole":     {"diseases": ["GERD", "peptic ulcer"],
                       "severity": "mild", "symptoms": ["heartburn", "acid reflux", "epigastric pain"]},
    "salbutamol":     {"diseases": ["asthma", "COPD"],
                       "severity": "moderate", "symptoms": ["wheezing", "dyspnea", "chest tightness"]},
    "prednisolone":   {"diseases": ["asthma", "rheumatoid arthritis", "lupus"],
                       "severity": "moderate", "symptoms": ["inflammation", "joint pain", "rash"]},
    "ciprofloxacin":  {"diseases": ["UTI", "pneumonia", "gastroenteritis"],
                       "severity": "moderate", "symptoms": ["dysuria", "fever", "diarrhea"]},
    "paracetamol":    {"diseases": ["fever", "pain"],
                       "severity": "mild", "symptoms": ["pyrexia", "headache", "myalgia"]},
    "ibuprofen":      {"diseases": ["pain", "inflammation", "fever"],
                       "severity": "mild", "symptoms": ["joint pain", "headache", "fever"]},
    "warfarin":       {"diseases": ["deep vein thrombosis", "atrial fibrillation", "pulmonary embolism"],
                       "severity": "severe", "symptoms": ["chest pain", "leg swelling", "palpitations"]},
    "levothyroxine":  {"diseases": ["hypothyroidism"],
                       "severity": "chronic", "symptoms": ["fatigue", "weight gain", "cold intolerance"]},
    "metoprolol":     {"diseases": ["hypertension", "angina", "heart failure"],
                       "severity": "moderate", "symptoms": ["chest pain", "palpitations", "dyspnea"]},
    "furosemide":     {"diseases": ["heart failure", "edema", "hypertension"],
                       "severity": "moderate", "symptoms": ["edema", "dyspnea", "ascites"]},
    "clopidogrel":    {"diseases": ["myocardial infarction", "stroke", "peripheral artery disease"],
                       "severity": "severe", "symptoms": ["chest pain", "TIA", "claudication"]},
    "amlodipine":     {"diseases": ["hypertension", "angina"],
                       "severity": "moderate", "symptoms": ["chest pain", "high blood pressure"]},
    "sertraline":     {"diseases": ["depression", "anxiety", "OCD"],
                       "severity": "moderate", "symptoms": ["low mood", "anxiety", "insomnia"]},
    "gabapentin":     {"diseases": ["epilepsy", "neuropathic pain"],
                       "severity": "moderate", "symptoms": ["seizures", "neuropathy", "pain"]},
    "tramadol":       {"diseases": ["moderate pain", "neuropathic pain"],
                       "severity": "moderate", "symptoms": ["chronic pain", "post-surgical pain"]},
    "doxycycline":    {"diseases": ["malaria", "Lyme disease", "acne"],
                       "severity": "mild", "symptoms": ["rash", "fever", "joint pain"]},
    "fluconazole":    {"diseases": ["candidiasis", "fungal infection"],
                       "severity": "mild", "symptoms": ["discharge", "itching", "oral thrush"]},
    "pantoprazole":   {"diseases": ["GERD", "peptic ulcer", "H. pylori"],
                       "severity": "mild", "symptoms": ["heartburn", "epigastric pain"]},
    "losartan":       {"diseases": ["hypertension", "diabetic nephropathy"],
                       "severity": "chronic", "symptoms": ["high blood pressure", "proteinuria"]},
    "methotrexate":   {"diseases": ["rheumatoid arthritis", "psoriasis", "cancer"],
                       "severity": "severe", "symptoms": ["joint pain", "skin lesions"]},
    "tamoxifen":      {"diseases": ["breast cancer"],
                       "severity": "severe", "symptoms": ["breast lump", "nipple discharge"]},
    "levodopa":       {"diseases": ["Parkinson's disease"],
                       "severity": "severe", "symptoms": ["tremor", "rigidity", "bradykinesia"]},
    "donepezil":      {"diseases": ["Alzheimer's disease", "dementia"],
                       "severity": "severe", "symptoms": ["memory loss", "confusion"]},
    "albuterol":      {"diseases": ["asthma", "COPD", "bronchospasm"],
                       "severity": "moderate", "symptoms": ["wheezing", "dyspnea", "chest tightness"]},
}

# Fuzzy match abbreviations
MED_ABBREVIATIONS = {
    "amox": "amoxicillin", "azithro": "azithromycin",
    "metf": "metformin",   "ins": "insulin",
    "lisin": "lisinopril", "atorv": "atorvastatin",
    "omep": "omeprazole",  "salb": "salbutamol",
    "pred": "prednisolone", "cipro": "ciprofloxacin",
    "pcm":  "paracetamol", "ibu":  "ibuprofen",
    "warf": "warfarin",    "levo": "levothyroxine",
    "metop": "metoprolol", "furo": "furosemide",
    "clop": "clopidogrel", "amlo": "amlodipine",
    "sert": "sertraline",  "gaba": "gabapentin",
}
