import React, { useState, useEffect, useCallback } from 'react';
import type { ReportData, ExplanationMeta } from '../../types';
import { Spinner } from '../Spinner';

interface NLETabProps {
  reportData: ReportData;
  onSave: (explanation: string, meta: Omit<ExplanationMeta, 'savedAt' | 'authorId'>) => void;
}

type Tone = 'Concise' | 'Technical' | 'Patient-friendly';

const templates: Record<Tone, string> = {
  Concise:
    "AI analysis of the report for a [age]-year-old [sex] with symptoms of [symptoms] suggests a [condition] in the [organ] (confidence: [confidence]%). The finding was localized to the provided bounding box. The image is synthetic.",
  Technical:
    "The system performed OCR on the provided document, extracting key fields: age ([age]), sex ([sex]), and symptoms ([symptoms]). The classification model ([model]) predicted a [condition] in the [organ] with a calculated confidence of [confidence]%. Localization via segmentation mask places the finding at bounding box [bbox]. Explainable AI (XAI) analysis identified '[feature1]' and '[feature2]' as the top textual features influencing this prediction. The synthetic image was generated by the [generator] model conditioned on the predicted organ and condition.",
  'Patient-friendly':
    `This is a summary of an AI analysis of a medical report. It is for research only and is not a medical diagnosis.
- What was found: The AI identified symptoms including [symptoms].
- AI's prediction: Based on the report, the system thinks there might be a '[condition]' in the '[organ]' area.
- Important: The image you see is computer-generated and is not a real medical scan. Please consult with a qualified doctor for any health concerns.`,
};

// Helper to fill templates gracefully
const fillTemplate = (template: string, data: ReportData): string => {
  const primaryCondition = data.predictions.conditions[0];
  const tokens: Record<string, string | number | undefined> = {
      age: data.fields.age,
      sex: data.fields.sex,
      symptoms: data.fields.symptoms.join(', '),
      organ: data.predictions.organ,
      condition: primaryCondition?.label,
      confidence: primaryCondition ? (primaryCondition.confidence * 100).toFixed(0) : undefined,
      model: primaryCondition?.model,
      bbox: data.predictions.localization.bbox.join(', '),
      feature1: data.xai.text_features[0]?.feature,
      feature2: data.xai.text_features[1]?.feature,
      generator: data.xai.provenance.generator,
  };

  let filled = template;
  for (const key in tokens) {
    const value = tokens[key];
    const regex = new RegExp(`\\[${key}\\]`, 'g');
    if (value !== undefined && value !== null) {
      filled = filled.replace(regex, String(value));
    }
  }

  // Cleanup sentences with missing tokens
  return filled.replace(/[^.!?]*\[[^\]]+\][^.!?]*[.!?]/g, '').trim();
};


export const NLETab: React.FC<NLETabProps> = ({ reportData, onSave }) => {
  const [currentTone, setCurrentTone] = useState<Tone>('Concise');
  const [explanationText, setExplanationText] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [source, setSource] = useState<'client-draft' | 'server-draft' | 'user'>('client-draft');

  useEffect(() => {
    if (reportData.explanation && reportData.explanationMeta) {
      setExplanationText(reportData.explanation);
      setCurrentTone(reportData.explanationMeta.tone);
      setSource('user');
    } else {
      setExplanationText(fillTemplate(templates.Concise, reportData));
      setCurrentTone('Concise');
      setSource('client-draft');
    }
  }, [reportData]);

  const handleGenerate = useCallback((tone: Tone) => {
    setIsLoading(true);
    // Simulate server-side generation
    setTimeout(() => {
      setCurrentTone(tone);
      setExplanationText(fillTemplate(templates[tone], reportData));
      setSource('client-draft'); // In a real app, this might be 'server-draft'
      setIsEditing(false);
      setIsLoading(false);
    }, 500);
  }, [reportData]);

  const handleSave = () => {
    onSave(explanationText, { tone: currentTone, source: 'user' });
    setIsEditing(false);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(explanationText);
    // Add toast notification here in a real app
  };
  
  const handleDownload = () => {
    const blob = new Blob([explanationText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-${reportData.id}-explanation.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 bg-white dark:bg-gray-800/50 rounded-lg border border-gray-200 dark:border-gray-700 space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">Generate Explanation</h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Select a tone to generate a new AI-drafted explanation of the findings.</p>
        <div className="mt-4 flex flex-wrap gap-3">
          {(['Concise', 'Technical', 'Patient-friendly'] as Tone[]).map((tone) => (
            <button
              key={tone}
              onClick={() => handleGenerate(tone)}
              disabled={isLoading}
              className={`px-4 py-2 text-sm font-semibold rounded-md transition ${
                currentTone === tone && !isEditing
                  ? 'bg-indigo-600 text-white'
                  : 'bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 hover:bg-gray-300 dark:hover:bg-gray-600'
              } disabled:opacity-50`}
            >
              {tone}
            </button>
          ))}
        </div>
      </div>

      <div className="relative">
         {isLoading && (
            <div className="absolute inset-0 bg-white/50 dark:bg-gray-900/50 flex items-center justify-center rounded-lg z-10">
                <Spinner />
            </div>
         )}
        <textarea
          value={explanationText}
          onChange={(e) => {
            setExplanationText(e.target.value);
            if (!isEditing) setIsEditing(true);
          }}
          className="w-full h-64 p-4 font-mono text-sm bg-gray-50 dark:bg-gray-900 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-indigo-500 focus:border-indigo-500 transition"
          placeholder="Explanation will appear here..."
        />
        <div className="absolute top-2 right-2 text-xs font-semibold px-2 py-1 rounded-full bg-opacity-80
            ${source === 'user' ? 'bg-green-100 text-green-800' : 'bg-blue-100 text-blue-800'}">
            {source === 'user' ? 'User Saved' : 'AI Draft'}
        </div>
      </div>
      
      <div className="flex flex-wrap justify-end gap-3">
        <button onClick={handleCopy} className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-200 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600 transition">Copy</button>
        <button onClick={handleDownload} className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-200 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-md hover:bg-gray-50 dark:hover:bg-gray-600 transition">Download .txt</button>
        {isEditing && (
             <button onClick={() => setIsEditing(false)} className="px-4 py-2 text-sm font-medium text-white bg-gray-500 hover:bg-gray-600 rounded-md transition">Cancel</button>
        )}
        <button
          onClick={handleSave}
          disabled={!isEditing}
          className="px-6 py-2 text-sm font-semibold text-white bg-indigo-600 rounded-md hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
        >
          Save Explanation
        </button>
      </div>
    </div>
  );
};
