"""
Curated Symptom-Disease Association Database
Association strengths: 0.0 (unrelated) to 1.0 (pathognomonic)
"""

SYMPTOM_DISEASE_ASSOCIATIONS = {
    "pneumonia": {
        "fever":                0.85,
        "cough":                0.90,
        "productive cough":     0.85,
        "dyspnea":              0.80,
        "crackles":             0.90,
        "shortness of breath":  0.80,
        "chest pain":           0.60,
        "low oxygen":           0.75,
        "spo2":                 0.75,
        "sputum":               0.70,
        "tachypnea":            0.75,
        "consolidation":        0.85,
    },
    "glioma": {
        "headache":             0.70,
        "seizure":              0.80,
        "nausea":               0.60,
        "vomiting":             0.60,
        "blurred vision":       0.65,
        "cognitive changes":    0.70,
        "focal neurological":   0.85,
        "papilledema":          0.75,
        "hemiparesis":          0.75,
    },
    "melanoma": {
        "irregular mole":       0.90,
        "asymmetric lesion":    0.90,
        "color variation":      0.85,
        "border irregularity":  0.85,
        "diameter >6mm":        0.80,
        "evolving lesion":      0.80,
        "skin lesion":          0.75,
        "ulceration":           0.70,
    },
    "diabetic retinopathy": {
        "floaters":             0.75,
        "blurred vision":       0.70,
        "dark spots":           0.75,
        "visual acuity loss":   0.80,
        "diabetes":             0.90,
        "high hba1c":           0.85,
        "hba1c":                0.85,
        "microaneurysm":        0.90,
        "hemorrhage":           0.85,
    },
    "tuberculosis": {
        "productive cough":     0.85,
        "hemoptysis":           0.90,
        "night sweats":         0.85,
        "weight loss":          0.80,
        "fever":                0.75,
        "fatigue":              0.70,
        "lymphadenopathy":      0.75,
    },
    "myocardial infarction": {
        "chest pain":           0.90,
        "crushing pain":        0.95,
        "radiation to arm":     0.85,
        "dyspnea":              0.75,
        "diaphoresis":          0.80,
        "nausea":               0.65,
        "ecg changes":          0.90,
        "elevated troponin":    0.95,
    },
    "appendicitis": {
        "right lower quadrant pain": 0.90,
        "rebound tenderness":        0.85,
        "nausea":                    0.70,
        "vomiting":                  0.70,
        "fever":                     0.75,
        "anorexia":                  0.70,
        "mcburney's point":          0.90,
    },
    "asthma": {
        "wheezing":             0.90,
        "dyspnea":              0.80,
        "chest tightness":      0.85,
        "cough":                0.75,
        "nocturnal symptoms":   0.80,
        "allergic history":     0.70,
        "reversible airflow":   0.90,
    },
    "urinary tract infection": {
        "dysuria":              0.90,
        "frequency":            0.85,
        "urgency":              0.80,
        "suprapubic pain":      0.75,
        "hematuria":            0.70,
        "fever":                0.60,
        "cloudy urine":         0.75,
    },
    "lung cancer": {
        "cough":                0.75,
        "hemoptysis":           0.85,
        "chest pain":           0.70,
        "weight loss":          0.80,
        "dyspnea":              0.75,
        "fatigue":              0.65,
        "wheezing":             0.60,
    },
    "breast cancer": {
        "breast lump":          0.90,
        "nipple discharge":     0.80,
        "skin changes":         0.75,
        "pain":                 0.50,
        "swelling":             0.65,
    },
    "kidney stone": {
        "flank pain":           0.90,
        "hematuria":            0.85,
        "nausea":               0.65,
        "vomiting":             0.65,
        "dysuria":              0.60,
        "frequency":            0.55,
    },
}

# Clinical importance weights per entity type
ENTITY_IMPORTANCE_WEIGHTS = {
    "symptoms":         1.0,
    "diseases":         0.9,
    "diagnostic_tests": 0.8,
    "medications":      0.6,
    "anatomical_refs":  0.4,
}

# Modality routing per top disease
DISEASE_TO_MODALITY = {
    "pneumonia":               "chest_xray",
    "tuberculosis":            "chest_xray",
    "asthma":                  "chest_xray",
    "glioma":                  "brain_mri",
    "brain tumor":             "brain_mri",
    "meningioma":              "brain_mri",
    "melanoma":                "dermoscopy",
    "skin cancer":             "dermoscopy",
    "diabetic retinopathy":    "fundus",
    "myocardial infarction":   "chest_xray",
    "lung cancer":             "chest_ct",
    "breast cancer":           "breast_mri",
    "kidney stone":            "kidney_ct",
    "appendicitis":            "abdominal_ct",
    "urinary tract infection":  "abdominal_ct",
    "default":                 "chest_xray",
}
