"""
Stage 6 — Structured Clinical Explanation via Ollama medgemma:4b.
Passes the full pipeline context for a rich, accurate clinical narrative.
Falls back to deterministic template if Ollama is unavailable.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import requests

OLLAMA_BASE   = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
EXPLAIN_MODEL = "medgemma:4b"
TIMEOUT       = 180


def _template_summary(report_data: dict) -> str:
    fields     = report_data.get("fields", {})
    preds      = report_data.get("predictions", {})
    conditions = preds.get("conditions", [])
    top        = conditions[0] if conditions else {}
    diff       = conditions[1:3] if len(conditions) > 1 else []

    age        = fields.get("age", "unknown")
    sex        = fields.get("sex", "unknown")
    symptoms   = fields.get("symptoms", []) or ["unspecified symptoms"]
    organ      = preds.get("organ", "unspecified organ")
    condition  = top.get("label", "unspecified condition")
    confidence = round(float(top.get("confidence", 0.5)) * 100, 1)
    diff_str   = "; ".join(f"{c['label']} ({round(c['confidence']*100,1)}%)" for c in diff) if diff else "none"

    return (
        f"CLINICAL SUMMARY: A {age}-year-old {sex} patient presents with {', '.join(symptoms[:5])} "
        f"involving the {organ} system.\n\n"
        f"PRIMARY DIAGNOSIS: AI analysis identifies {condition} as the most likely diagnosis "
        f"with an estimated confidence of {confidence}%. {top.get('reasoning', '')}\n\n"
        f"DIFFERENTIAL DIAGNOSIS: Alternative considerations include {diff_str}.\n\n"
        f"DISCLAIMER: These findings are AI-generated by TraceMD for research purposes only "
        f"and must not be used as a standalone clinical diagnosis."
    )


def run_explainer(report_data: dict) -> str:
    fields     = report_data.get("fields", {})
    preds      = report_data.get("predictions", {})
    conditions = preds.get("conditions", [])
    xai        = report_data.get("xai", {})
    ocr_text   = report_data.get("ocrText", "")

    top    = conditions[0] if conditions else {}
    diff   = conditions[1:3] if len(conditions) > 1 else []
    shap   = xai.get("shap_table", [])
    feats  = xai.get("text_features", [])[:6]

    diff_str = "\n".join(
        f"  - {c['label']} ({round(c['confidence']*100,1)}%): {c.get('reasoning', 'Alternative consideration')}"
        for c in diff
    ) if diff else "  - No strong alternatives identified"

    feat_str = "\n".join(
        f"  - {f['feature']}: weight={f['weight']}"
        for f in feats
    ) if feats else "  - No features extracted"

    shap_str = "\n".join(
        f"  - {s['feature']}: value={s['value']}, SHAP impact={s['impact']:+.3f}"
        for s in shap[:3]
    ) if shap else "  - SHAP not available"

    prompt = f"""You are a senior clinical physician AI generating a structured diagnostic report.

PATIENT DEMOGRAPHICS:
- Age: {fields.get('age', 'unknown')} | Sex: {fields.get('sex', 'unknown')}
- Presenting symptoms: {', '.join(fields.get('symptoms', ['none reported']))}
- Affected organ system: {preds.get('organ', 'unknown')}

PRIMARY AI DIAGNOSIS:
- Condition: {top.get('label', 'unknown')}
- Confidence: {round(top.get('confidence', 0) * 100, 1)}%
- Clinical reasoning: {top.get('reasoning', 'Clinical inference')}

DIFFERENTIAL DIAGNOSES:
{diff_str}

XAI FEATURE IMPORTANCE:
{feat_str}

SHAP EXPLAINABILITY:
{shap_str}

ORIGINAL DOCUMENT EXCERPT (first 600 chars):
{ocr_text[:600] if ocr_text else 'Not available'}

Generate a structured clinical AI report with EXACTLY these four sections and headings:

CLINICAL SUMMARY:
[2-3 sentences. Concisely state who the patient is, key presenting symptoms, and the affected organ system.]

PRIMARY DIAGNOSIS:
[2-3 sentences. Name the condition, state the confidence level, and explain WHY — citing the specific clinical features, vitals, or findings that support this diagnosis.]

DIFFERENTIAL DIAGNOSIS:
[1-2 sentences per alternative. For each differential, name it, give its confidence, and explain what makes it less likely than the primary.]

DISCLAIMER:
[One sentence. State clearly that this is AI-generated research output from TraceMD and must not be used for clinical diagnosis or treatment decisions.]

Keep total response under 300 words. Use precise clinical language. Do not add any text outside these four sections."""

    print("  [Explainer] Sending full context to Ollama medgemma:4b...")
    try:
        resp = requests.post(
            f"{OLLAMA_BASE}/api/generate",
            json={"model": EXPLAIN_MODEL, "prompt": prompt, "stream": False},
            timeout=TIMEOUT,
        )
        resp.raise_for_status()
        summary = resp.json().get("response", "").strip()
    except requests.exceptions.ConnectionError:
        print("  [Explainer] WARNING: Ollama unavailable — using template summary")
        return _template_summary(report_data)
    except Exception as e:
        print(f"  [Explainer] WARNING: {e} — using template summary")
        return _template_summary(report_data)

    print(f"  [Explainer] Generated {len(summary)} chars")
    if not summary or len(summary) < 60:
        return _template_summary(report_data)
    return summary
