import React, { useState, useEffect, useCallback } from 'react';
import type { ReportData } from '../../types';

interface NLExplanationTabProps {
  reportData: ReportData;
  onReset: () => void;
}

type Tone = 'Concise' | 'Technical' | 'Patient-friendly';

const templates: Record<Tone, string> = {
  Concise:
    `AI analysis of the report for a [age]-year-old [sex] patient with symptoms of [symptoms] suggests a [condition] in the [organ] (confidence: [confidence]%). The finding was localized to the provided bounding box. The image is synthetic and not for diagnostic use.`,
  Technical:
    `The system performed OCR on the provided document, extracting key fields: age ([age]), sex ([sex]), and symptoms ([symptoms]). The classification model ([model]) predicted a [condition] in the [organ] with a calculated confidence of [confidence]%. Localization via segmentation mask places the finding at bounding box [bbox]. Explainable AI (XAI) analysis identified '[feature1]' and '[feature2]' as the top textual features influencing this prediction. The synthetic image was generated by the [generator] model conditioned on the predicted organ and condition.`,
  'Patient-friendly':
    `This is a summary of an AI analysis of a medical report. It is for research only and is not a medical diagnosis.\n\n- What was found: The AI identified symptoms including [symptoms].\n- AI's prediction: Based on the report, the system found possible '[condition]' in the '[organ]' area.\n- Important: The image shown is computer-generated and is not a real medical scan. Please consult with a qualified doctor for any health concerns.`,
};

const fillTemplate = (template: string, data: ReportData): string => {
  const primary = data.predictions.conditions[0];
  const tokens: Record<string, string | number | undefined> = {
    age: data.fields.age,
    sex: data.fields.sex,
    symptoms: data.fields.symptoms.join(', '),
    organ: data.predictions.organ,
    condition: primary?.label,
    confidence: primary ? (primary.confidence * 100).toFixed(0) : undefined,
    model: primary?.model,
    bbox: data.predictions.localization.bbox.join(', '),
    feature1: data.xai.text_features[0]?.feature,
    feature2: data.xai.text_features[1]?.feature,
    generator: data.xai.provenance.generator,
  };

  let filled = template;
  for (const key in tokens) {
    const value = tokens[key];
    const regex = new RegExp(`\\[${key}\\]`, 'g');
    if (value !== undefined && value !== null) {
      filled = filled.replace(regex, String(value));
    }
  }
  return filled;
};

export const NLExplanationTab: React.FC<NLExplanationTabProps> = ({ reportData, onReset }) => {
  const [currentTone, setCurrentTone] = useState<Tone>('Concise');
  const [text, setText] = useState('');
  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    if (reportData.xai.naturalLanguageSummary) {
      setText(reportData.xai.naturalLanguageSummary);
    } else {
      setText(fillTemplate(templates.Concise, reportData));
    }
  }, [reportData]);

  const handleGenerate = useCallback((tone: Tone) => {
    setCurrentTone(tone);
    setText(fillTemplate(templates[tone], reportData));
    setIsEditing(false);
  }, [reportData]);

  const handleCopy = () => navigator.clipboard.writeText(text);

  const handleDownload = () => {
    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-${reportData.id}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-6 bg-[var(--bg-card)] rounded-lg border border-[var(--border-color)] space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-[var(--text-primary)]">Generate Explanation</h3>
        <p className="text-sm text-[var(--text-secondary)] mt-1">Select a tone to generate a new explanation of the findings.</p>
        <div className="mt-4 flex flex-wrap gap-3">
          {(['Concise', 'Technical', 'Patient-friendly'] as Tone[]).map((tone) => (
            <button
              key={tone}
              onClick={() => handleGenerate(tone)}
              className={`px-4 py-2 text-sm font-semibold rounded-md transition ${
                currentTone === tone && !isEditing
                  ? 'bg-[var(--accent)] text-white'
                  : 'bg-[var(--bg-primary)] text-[var(--text-secondary)] hover:bg-[var(--bg-card-hover)]'
              }`}
            >
              {tone}
            </button>
          ))}
        </div>
      </div>

      <textarea
        value={text}
        onChange={(e) => { setText(e.target.value); if (!isEditing) setIsEditing(true); }}
        className="w-full h-64 p-4 font-mono text-sm bg-[var(--bg-primary)] border border-[var(--border-color)] rounded-lg text-[var(--text-primary)] focus:ring-[var(--accent)] focus:border-[var(--accent)] transition resize-none"
        placeholder="Explanation will appear here…"
      />

      <div className="flex flex-wrap justify-end gap-3">
        <button onClick={handleCopy} className="px-4 py-2 text-sm font-medium text-[var(--text-secondary)] bg-[var(--bg-primary)] border border-[var(--border-color)] rounded-md hover:bg-[var(--bg-card-hover)] transition">
          Copy
        </button>
        <button onClick={handleDownload} className="px-4 py-2 text-sm font-medium text-white bg-[var(--accent)] rounded-md hover:bg-[var(--accent-light)] transition">
          Download Report
        </button>
        <button onClick={onReset} className="px-4 py-2 text-sm font-medium text-[var(--text-secondary)] border border-[var(--border-color)] rounded-md hover:bg-[var(--bg-card-hover)] transition">
          Start New Analysis
        </button>
      </div>
    </div>
  );
};
